[package]
name = "uu_env"
version = "0.0.23"
authors = ["uutils developers"]
license = "MIT"
description = "env ~ (uutils) set each NAME to VALUE in the environment and run COMMAND"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/env"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2021"

[lib]
path = "src/env.rs"

[dependencies]
clap = { workspace = true }
rust-ini = { workspace = true }
uucore = { workspace = true, features = ["signals"] }
quoted-string = "0.6.1"
escape_string = "0.1.2"
shlex = "1.2.0"
oursh = "0.4.4"
#nsh = "0.4.2"
nsh ={ path = "/home/uli/dev_rust/nsh" }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["signal"] }


[[bin]]
name = "env"
path = "src/main.rs"
